const COUNTRY_CODES = {
  AF: ['afghanistan', 'afghanistan', 'islamic state of afghanistan'],
  AO: ['angola', 'angola', "people's republic of angola"],
  AL: ['albania', 'albania', 'republic of albania'],
  AE: ['united arab emirates', 'united arab emirates', 'united arab emirates'],
  AR: ['argentina', 'argentina', 'argentine republic'],
  AM: ['armenia', 'armenia', 'republic of armenia'],
  AQ: ['antarctica', 'antarctica'],
  TF: [
    'fr. s. antarctic lands',
    'french southern and antarctic lands',
    'territory of the french southern and antarctic lands',
  ],
  AU: ['australia', 'australia', 'commonwealth of australia'],
  AT: ['austria', 'austria', 'republic of austria'],
  AZ: ['azerbaijan', 'azerbaijan', 'republic of azerbaijan'],
  BI: ['burundi', 'burundi', 'republic of burundi'],
  BE: ['belgium', 'belgium', 'kingdom of belgium'],
  BJ: ['benin', 'benin', 'republic of benin'],
  BF: ['burkina faso', 'burkina faso', 'burkina faso'],
  BD: ['bangladesh', 'bangladesh', "people's republic of bangladesh"],
  BG: ['bulgaria', 'bulgaria', 'republic of bulgaria'],
  BS: ['bahamas', 'bahamas', 'commonwealth of the bahamas'],
  BA: ['bosnia and herz.', 'bosnia and herzegovina', 'bosnia and herzegovina'],
  BY: ['belarus', 'belarus', 'republic of belarus'],
  BZ: ['belize', 'belize', 'belize'],
  BO: [
    'bolivia',
    'bolivia',
    'plurinational state of bolivia',
    'bolivia (plurinational state of)',
  ],
  BR: ['brazil', 'brazil', 'federative republic of brazil'],
  BN: ['brunei', 'brunei darussalam', 'negara brunei darussalam'],
  BT: ['bhutan', 'bhutan', 'kingdom of bhutan'],
  BW: ['botswana', 'botswana', 'republic of botswana'],
  CF: [
    'central african rep.',
    'central african republic',
    'central african republic',
  ],
  CA: ['canada', 'canada', 'canada'],
  CH: ['switzerland', 'switzerland', 'swiss confederation'],
  CL: ['chile', 'chile', 'republic of chile'],
  CN: ['china', 'china', "people's republic of china"],
  CI: [
    "côte d'ivoire",
    'republic of ivory coast',
    'cote divoire',
    'côte d’ivoire',
  ],
  CM: ['cameroon', 'cameroon', 'republic of cameroon'],
  CD: [
    'dem. rep. congo',
    'democratic republic of the congo',
    'democratic republic of the congo',
  ],
  CG: ['congo', 'republic of the congo', 'republic of the congo'],
  CO: ['colombia', 'colombia', 'republic of colombia'],
  CR: ['costa rica', 'costa rica', 'republic of costa rica'],
  CU: ['cuba', 'cuba', 'republic of cuba'],
  '-99': [
    'n. cyprus',
    'northern cyprus',
    'turkish republic of northern cyprus',
  ],
  CY: ['cyprus', 'cyprus', 'republic of cyprus'],
  CZ: ['czechia', 'czech republic', 'czech republic'],
  DE: ['germany', 'germany', 'federal republic of germany'],
  DJ: ['djibouti', 'djibouti', 'republic of djibouti'],
  DK: ['denmark', 'denmark', 'kingdom of denmark'],
  DO: ['dominican rep.', 'dominican republic', 'dominican republic'],
  DZ: ['algeria', 'algeria', "people's democratic republic of algeria"],
  EC: ['ecuador', 'ecuador', 'republic of ecuador'],
  EG: ['egypt', 'egypt', 'arab republic of egypt'],
  ER: ['eritrea', 'eritrea', 'state of eritrea'],
  ES: ['spain', 'spain', 'kingdom of spain'],
  EE: ['estonia', 'estonia', 'republic of estonia'],
  ET: ['ethiopia', 'ethiopia', 'federal democratic republic of ethiopia'],
  FI: ['finland', 'finland', 'republic of finland'],
  FJ: ['fiji', 'fiji', 'republic of fiji'],
  FK: ['falkland is.', 'falkland islands', 'falkland islands'],
  FR: ['france', 'france', 'french republic'],
  GA: ['gabon', 'gabon', 'gabonese republic'],
  GB: [
    'united kingdom',
    'united kingdom',
    'united kingdom of great britain and northern ireland',
    'the united kingdom',
  ],
  GE: ['georgia', 'georgia', 'georgia'],
  GH: ['ghana', 'ghana', 'republic of ghana'],
  GN: ['guinea', 'guinea', 'republic of guinea'],
  GM: ['gambia', 'the gambia', 'republic of the gambia'],
  GW: ['guinea-bissau', 'guinea-bissau', 'republic of guinea-bissau'],
  GQ: ['eq. guinea', 'equatorial guinea', 'republic of equatorial guinea'],
  GR: ['greece', 'greece', 'hellenic republic'],
  GL: ['greenland', 'greenland', 'greenland'],
  GT: ['guatemala', 'guatemala', 'republic of guatemala'],
  GY: ['guyana', 'guyana', 'co-operative republic of guyana'],
  HN: ['honduras', 'honduras', 'republic of honduras'],
  HR: ['croatia', 'croatia', 'republic of croatia'],
  HT: ['haiti', 'haiti', 'republic of haiti'],
  HU: ['hungary', 'hungary', 'republic of hungary'],
  ID: ['indonesia', 'indonesia', 'republic of indonesia'],
  IN: ['india', 'india', 'republic of india'],
  IE: ['ireland', 'ireland', 'ireland'],
  IR: [
    'iran',
    'iran',
    'islamic republic of iran',
    'iran (islamic republic of)',
  ],
  IQ: ['iraq', 'iraq', 'republic of iraq'],
  IS: ['iceland', 'iceland', 'republic of iceland'],
  IL: ['israel', 'israel', 'state of israel'],
  IT: ['italy', 'italy', 'italian republic'],
  JM: ['jamaica', 'jamaica', 'jamaica'],
  JO: ['jordan', 'jordan', 'hashemite kingdom of jordan'],
  JP: ['japan', 'japan', 'japan'],
  KZ: ['kazakhstan', 'kazakhstan', 'republic of kazakhstan'],
  KE: ['kenya', 'kenya', 'republic of kenya'],
  KG: ['kyrgyzstan', 'kyrgyzstan', 'kyrgyz republic'],
  KH: ['cambodia', 'cambodia', 'kingdom of cambodia'],
  KR: ['south korea', 'republic of korea', 'republic of korea'],
  XK: ['kosovo', 'kosovo', 'republic of kosovo'],
  KW: ['kuwait', 'kuwait', 'state of kuwait'],
  LA: ['laos', 'lao pdr', "lao people's democratic republic"],
  LB: ['lebanon', 'lebanon', 'lebanese republic'],
  LR: ['liberia', 'liberia', 'republic of liberia'],
  LY: ['libya', 'libya', 'libya'],
  LK: ['sri lanka', 'sri lanka', 'democratic socialist republic of sri lanka'],
  LS: ['lesotho', 'lesotho', 'kingdom of lesotho'],
  LT: ['lithuania', 'lithuania', 'republic of lithuania'],
  LU: ['luxembourg', 'luxembourg', 'grand duchy of luxembourg'],
  LV: ['latvia', 'latvia', 'republic of latvia'],
  MA: ['morocco', 'morocco', 'kingdom of morocco'],
  MD: ['moldova', 'moldova', 'republic of moldova'],
  MG: ['madagascar', 'madagascar', 'republic of madagascar'],
  MX: ['mexico', 'mexico', 'united mexican states'],
  MK: [
    'macedonia',
    'macedonia',
    'former yugoslav republic of macedonia',
    'north macedonia',
    'the former yugoslav republic of macedonia',
  ],
  ML: ['mali', 'mali', 'republic of mali'],
  MM: ['myanmar', 'myanmar', 'republic of the union of myanmar'],
  ME: ['montenegro', 'montenegro', 'montenegro'],
  MN: ['mongolia', 'mongolia', 'mongolia'],
  MZ: ['mozambique', 'mozambique', 'republic of mozambique'],
  MR: ['mauritania', 'mauritania', 'islamic republic of mauritania'],
  MW: ['malawi', 'malawi', 'republic of malawi'],
  MY: ['malaysia', 'malaysia', 'malaysia'],
  NA: ['namibia', 'namibia', 'republic of namibia'],
  NC: ['new caledonia', 'new caledonia', 'new caledonia'],
  NE: ['niger', 'niger', 'republic of niger'],
  NG: ['nigeria', 'nigeria', 'federal republic of nigeria'],
  NI: ['nicaragua', 'nicaragua', 'republic of nicaragua'],
  NL: ['netherlands', 'netherlands', 'kingdom of the netherlands'],
  NO: ['norway', 'norway', 'kingdom of norway'],
  NP: ['nepal', 'nepal', 'nepal'],
  NZ: ['new zealand', 'new zealand', 'new zealand'],
  OM: ['oman', 'oman', 'sultanate of oman'],
  PK: ['pakistan', 'pakistan', 'islamic republic of pakistan'],
  PA: ['panama', 'panama', 'republic of panama'],
  PE: ['peru', 'peru', 'republic of peru'],
  PH: ['philippines', 'philippines', 'republic of the philippines'],
  PG: [
    'papua new guinea',
    'papua new guinea',
    'independent state of papua new guinea',
  ],
  PL: ['poland', 'poland', 'republic of poland'],
  PR: ['puerto rico', 'puerto rico', 'commonwealth of puerto rico'],
  KP: [
    'north korea',
    'dem. rep. korea',
    "democratic people's republic of korea",
  ],
  PT: ['portugal', 'portugal', 'portuguese republic'],
  PY: ['paraguay', 'paraguay', 'republic of paraguay'],
  PS: [
    'palestine',
    'palestine',
    'west bank and gaza',
    'occupied palestinian territory',
  ],
  QA: ['qatar', 'qatar', 'state of qatar'],
  RO: ['romania', 'romania', 'romania'],
  RU: ['russia', 'russian federation', 'russian federation'],
  RW: ['rwanda', 'rwanda', 'republic of rwanda'],
  EH: ['w. sahara', 'western sahara', 'sahrawi arab democratic republic'],
  SA: ['saudi arabia', 'saudi arabia', 'kingdom of saudi arabia'],
  SD: ['sudan', 'sudan', 'republic of the sudan'],
  SS: ['s. sudan', 'south sudan', 'republic of south sudan'],
  SN: ['senegal', 'senegal', 'republic of senegal'],
  SB: ['solomon is.', 'solomon islands', ''],
  SL: ['sierra leone', 'sierra leone', 'republic of sierra leone'],
  SV: ['el salvador', 'el salvador', 'republic of el salvador'],
  SO: ['somalia', 'somalia', 'federal republic of somalia'],
  RS: ['serbia', 'serbia', 'republic of serbia'],
  SR: ['suriname', 'suriname', 'republic of suriname'],
  SK: ['slovakia', 'slovakia', 'slovak republic'],
  SI: ['slovenia', 'slovenia', 'republic of slovenia'],
  SE: ['sweden', 'sweden', 'kingdom of sweden'],
  SZ: ['swaziland', 'swaziland', 'kingdom of swaziland'],
  SY: ['syria', 'syria', 'syrian arab republic'],
  TD: ['chad', 'chad', 'republic of chad'],
  TG: ['togo', 'togo', 'togolese republic'],
  TH: ['thailand', 'thailand', 'kingdom of thailand'],
  TJ: ['tajikistan', 'tajikistan', 'republic of tajikistan'],
  TM: ['turkmenistan', 'turkmenistan', 'turkmenistan'],
  TL: ['timor-leste', 'timor-leste', 'democratic republic of timor-leste'],
  TT: [
    'trinidad and tobago',
    'trinidad and tobago',
    'republic of trinidad and tobago',
  ],
  TN: ['tunisia', 'tunisia', 'republic of tunisia'],
  TR: ['turkey', 'turkey', 'republic of turkey'],
  TW: ['taiwan', 'taiwan', ''],
  TZ: ['tanzania', 'tanzania', 'united republic of tanzania'],
  UG: ['uganda', 'uganda', 'republic of uganda'],
  UA: ['ukraine', 'ukraine', 'ukraine'],
  UY: ['uruguay', 'uruguay', 'oriental republic of uruguay'],
  US: ['united states of america', 'united states', 'united states of america'],
  UZ: ['uzbekistan', 'uzbekistan', 'republic of uzbekistan'],
  VE: ['venezuela', 'venezuela', 'bolivarian republic of venezuela'],
  VN: ['vietnam', 'vietnam', 'socialist republic of vietnam', 'viet nam'],
  VU: ['vanuatu', 'vanuatu', 'republic of vanuatu'],
  YE: ['yemen', 'yemen', 'republic of yemen'],
  ZA: ['south africa', 'south africa', 'republic of south africa'],
  ZM: ['zambia', 'zambia', 'republic of zambia'],
  ZW: ['zimbabwe', 'zimbabwe', 'republic of zimbabwe'],
  MT: ['malta'],
  LI: ['liechtenstein'],
  SG: ['singapore'],
  BH: ['bahrain'],
  MV: ['maldives'],
  SM: ['san marino'],
  VA: ['holy see', 'holy see (vatican city)'],
  AD: ['andorra'],
  MC: ['monaco'],
  PF: ['french polynesia'],
  FO: ['faroe islands'],
  GI: ['gibraltar'],
  GG: ['guernsey'],
  GF: ['french guiana'],
  MQ: ['martinique'],
  MF: ['saint martin'],
  BL: ['saint barthelemy'],
}

export default COUNTRY_CODES
