const COUNTRY_CODES: { [key: string]: string[] } = {
  AF: ['Afghanistan', 'afghanistan', 'islamic state of afghanistan'],
  AO: ['Angola', 'angola', "people's republic of angola"],
  AL: ['Albania', 'albania', 'republic of albania'],
  AE: ['Anited Arab Emirates', 'united arab emirates', 'united arab emirates'],
  AR: ['Argentina', 'argentina', 'argentine republic'],
  AM: ['Armenia', 'armenia', 'republic of armenia'],
  AQ: ['Antarctica', 'antarctica'],
  TF: [
    'French Southern and Antarctic Lands',
    'fr. s. antarctic lands',
    'territory of the french southern and antarctic lands',
  ],
  AU: ['Australia', 'australia', 'commonwealth of australia'],
  AT: ['Austria', 'austria', 'republic of austria'],
  AZ: ['Azerbaijan', 'azerbaijan', 'republic of azerbaijan'],
  BI: ['Burundi', 'burundi', 'republic of burundi'],
  BE: ['Belgium', 'belgium', 'kingdom of belgium'],
  BJ: ['Benin', 'benin', 'republic of benin'],
  BF: ['Burkina Faso', 'burkina faso', 'burkina faso'],
  BD: ['Bangladesh', 'bangladesh', "people's republic of bangladesh"],
  BG: ['Bulgaria', 'bulgaria', 'republic of bulgaria'],
  BS: ['Bahamas', 'bahamas', 'commonwealth of the bahamas'],
  BA: ['Bosnia and Herz.', 'bosnia and herzegovina', 'bosnia and herzegovina'],
  BY: ['Belarus', 'belarus', 'republic of belarus'],
  BZ: ['Belize', 'belize', 'belize'],
  BO: [
    'Bolivia',
    'bolivia',
    'plurinational state of bolivia',
    'bolivia (plurinational state of)',
  ],
  BR: ['Brazil', 'brazil', 'federative republic of brazil'],
  BN: ['brunei', 'brunei darussalam', 'negara brunei darussalam'],
  BT: ['bhutan', 'bhutan', 'kingdom of bhutan'],
  BW: ['botswana', 'botswana', 'republic of botswana'],
  CF: [
    'Central African Rep.',
    'central african republic',
    'central african republic',
  ],
  CA: ['Canada', 'canada', 'canada'],
  CH: ['Switzerland', 'switzerland', 'swiss confederation'],
  CL: ['Chile', 'chile', 'republic of chile'],
  CN: ['China', 'china', "people's republic of china"],
  CI: [
    'Ivory Coast',
    'Republic of Ivory Coast',
    "côte d'ivoire",
    'cote divoire',
    'côte d’ivoire',
  ],
  CM: ['Cameroon', 'cameroon', 'republic of cameroon'],
  CD: [
    'Dem. Rep. Congo',
    'democratic republic of the congo',
    'democratic republic of the congo',
  ],
  CG: ['Congo', 'republic of the congo', 'republic of the congo'],
  CO: ['Colombia', 'colombia', 'republic of colombia'],
  CR: ['Costa Rica', 'costa rica', 'republic of costa rica'],
  CU: ['Cuba', 'cuba', 'republic of cuba'],
  CY: ['Cyprus', 'cyprus', 'republic of cyprus'],
  CZ: ['Czechia', 'czech republic', 'czech republic'],
  DE: ['Germany', 'germany', 'federal republic of germany'],
  DJ: ['Djibouti', 'djibouti', 'republic of djibouti'],
  DK: ['Denmark', 'denmark', 'kingdom of denmark'],
  DO: ['Dominican Rep.', 'dominican republic', 'dominican republic'],
  DZ: ['Algeria', 'algeria', "people's democratic republic of algeria"],
  EC: ['Ecuador', 'ecuador', 'republic of ecuador'],
  EG: ['Egypt', 'egypt', 'arab republic of egypt'],
  ER: ['Eritrea', 'eritrea', 'state of eritrea'],
  ES: ['Spain', 'spain', 'kingdom of spain'],
  EE: ['Estonia', 'estonia', 'republic of estonia'],
  ET: ['Ethiopia', 'ethiopia', 'federal democratic republic of ethiopia'],
  FI: ['Finland', 'finland', 'republic of finland'],
  FJ: ['Fiji', 'fiji', 'republic of fiji'],
  FK: ['Falkland is.', 'falkland islands', 'falkland islands'],
  FR: ['France', 'france', 'french republic'],
  GA: ['Gabon', 'gabon', 'gabonese republic'],
  GB: [
    'United Kingdom',
    'united kingdom',
    'united kingdom of great britain and northern ireland',
    'the united kingdom',
  ],
  GE: ['Georgia', 'georgia', 'georgia'],
  GH: ['Ghana', 'ghana', 'republic of ghana'],
  GN: ['Guinea', 'guinea', 'republic of guinea'],
  GM: ['Gambia', 'the gambia', 'republic of the gambia'],
  GW: ['Guinea-bissau', 'guinea-bissau', 'republic of guinea-bissau'],
  GQ: ['Eq. Guinea', 'equatorial guinea', 'republic of equatorial guinea'],
  GR: ['Greece', 'greece', 'hellenic republic'],
  GL: ['Greenland', 'greenland', 'greenland'],
  GT: ['Guatemala', 'guatemala', 'republic of guatemala'],
  GY: ['Guyana', 'guyana', 'co-operative republic of guyana'],
  HN: ['Honduras', 'honduras', 'republic of honduras'],
  HR: ['Croatia', 'croatia', 'republic of croatia'],
  HT: ['Haiti', 'haiti', 'republic of haiti'],
  HU: ['Hungary', 'hungary', 'republic of hungary'],
  ID: ['Indonesia', 'indonesia', 'republic of indonesia'],
  IN: ['India', 'india', 'republic of india'],
  IE: ['Ireland', 'ireland', 'ireland'],
  IR: [
    'Iran',
    'iran',
    'islamic republic of iran',
    'iran (islamic republic of)',
  ],
  IQ: ['Iraq', 'iraq', 'republic of iraq'],
  IS: ['Iceland', 'iceland', 'republic of iceland'],
  IL: ['Israel', 'israel', 'state of israel'],
  IT: ['Italy', 'italy', 'italian republic'],
  JM: ['Jamaica', 'jamaica', 'jamaica'],
  JO: ['Jordan', 'jordan', 'hashemite kingdom of jordan'],
  JP: ['Japan', 'japan', 'japan'],
  KZ: ['Kazakhstan', 'kazakhstan', 'republic of kazakhstan'],
  KE: ['Kenya', 'kenya', 'republic of kenya'],
  KG: ['Kyrgyzstan', 'kyrgyzstan', 'kyrgyz republic'],
  KH: ['Cambodia', 'cambodia', 'kingdom of cambodia'],
  KR: ['South Korea', 'republic of korea', 'republic of korea'],
  XK: ['Kosovo', 'kosovo', 'republic of kosovo'],
  KW: ['Kuwait', 'kuwait', 'state of kuwait'],
  LA: ['Laos', 'lao pdr', "lao people's democratic republic"],
  LB: ['Lebanon', 'lebanon', 'lebanese republic'],
  LR: ['Liberia', 'liberia', 'republic of liberia'],
  LY: ['Libya', 'libya', 'libya'],
  LK: ['Sri Lanka', 'sri lanka', 'democratic socialist republic of sri lanka'],
  LS: ['Lesotho', 'lesotho', 'kingdom of lesotho'],
  LT: ['Lithuania', 'lithuania', 'republic of lithuania'],
  LU: ['Luxembourg', 'luxembourg', 'grand duchy of luxembourg'],
  LV: ['Latvia', 'latvia', 'republic of latvia'],
  MA: ['Morocco', 'morocco', 'kingdom of morocco'],
  MD: ['Moldova', 'moldova', 'republic of moldova'],
  MG: ['Madagascar', 'madagascar', 'republic of madagascar'],
  MX: ['Mexico', 'mexico', 'united mexican states'],
  MK: [
    'Macedonia',
    'macedonia',
    'former yugoslav republic of macedonia',
    'north macedonia',
    'the former yugoslav republic of macedonia',
  ],
  ML: ['Mali', 'mali', 'republic of mali'],
  MM: ['Myanmar', 'myanmar', 'republic of the union of myanmar'],
  ME: ['Montenegro', 'montenegro', 'montenegro'],
  MN: ['Mongolia', 'mongolia', 'mongolia'],
  MZ: ['Mozambique', 'mozambique', 'republic of mozambique'],
  MR: ['Mauritania', 'mauritania', 'islamic republic of mauritania'],
  MW: ['Malawi', 'malawi', 'republic of malawi'],
  MY: ['Malaysia', 'malaysia', 'malaysia'],
  NA: ['Namibia', 'namibia', 'republic of namibia'],
  NC: ['New Caledonia', 'new caledonia', 'new caledonia'],
  NE: ['Niger', 'niger', 'republic of niger'],
  NG: ['Nigeria', 'nigeria', 'federal republic of nigeria'],
  NI: ['Nicaragua', 'nicaragua', 'republic of nicaragua'],
  NL: ['Netherlands', 'netherlands', 'kingdom of the netherlands'],
  NO: ['Norway', 'norway', 'kingdom of norway'],
  NP: ['Nepal', 'nepal', 'nepal'],
  NZ: ['New Zealand', 'new zealand', 'new zealand'],
  OM: ['Oman', 'oman', 'sultanate of oman'],
  PK: ['Pakistan', 'pakistan', 'islamic republic of pakistan'],
  PA: ['Panama', 'panama', 'republic of panama'],
  PE: ['Peru', 'peru', 'republic of peru'],
  PH: ['Philippines', 'philippines', 'republic of the philippines'],
  PG: [
    'Papua new guinea',
    'papua new guinea',
    'independent state of papua new guinea',
  ],
  PL: ['Poland', 'poland', 'republic of poland'],
  PR: ['Puerto Rico', 'puerto rico', 'commonwealth of puerto rico'],
  KP: [
    'North Korea',
    'dem. rep. korea',
    "democratic people's republic of korea",
  ],
  PT: ['Portugal', 'portugal', 'portuguese republic'],
  PY: ['Paraguay', 'paraguay', 'republic of paraguay'],
  PS: [
    'Palestine',
    'palestine',
    'west bank and gaza',
    'occupied palestinian territory',
  ],
  QA: ['Qatar', 'qatar', 'state of qatar'],
  RO: ['Romania', 'romania', 'romania'],
  RU: ['Russia', 'russian federation', 'russian federation'],
  RW: ['Rwanda', 'rwanda', 'republic of rwanda'],
  EH: ['W. Sahara', 'western sahara', 'sahrawi arab democratic republic'],
  SA: ['Saudi Arabia', 'saudi arabia', 'kingdom of saudi arabia'],
  SD: ['Sudan', 'sudan', 'republic of the sudan'],
  SS: ['S. Sudan', 'south sudan', 'republic of south sudan'],
  SN: ['Senegal', 'senegal', 'republic of senegal'],
  SB: ['Solomon Is.', 'solomon islands', ''],
  SL: ['Sierra Leone', 'sierra leone', 'republic of sierra leone'],
  SV: ['El Salvador', 'el salvador', 'republic of el salvador'],
  SO: ['Somalia', 'somalia', 'federal republic of somalia'],
  RS: ['Serbia', 'serbia', 'republic of serbia'],
  SR: ['Suriname', 'suriname', 'republic of suriname'],
  SK: ['Slovakia', 'slovakia', 'slovak republic'],
  SI: ['Slovenia', 'slovenia', 'republic of slovenia'],
  SE: ['Sweden', 'sweden', 'kingdom of sweden'],
  SZ: ['Swaziland', 'swaziland', 'kingdom of swaziland'],
  SY: ['Syria', 'syria', 'syrian arab republic'],
  TD: ['Chad', 'chad', 'republic of chad'],
  TG: ['Togo', 'togo', 'togolese republic'],
  TH: ['Thailand', 'thailand', 'kingdom of thailand'],
  TJ: ['Tajikistan', 'tajikistan', 'republic of tajikistan'],
  TM: ['Turkmenistan', 'turkmenistan', 'turkmenistan'],
  TL: ['Timor-Leste', 'timor-leste', 'democratic republic of timor-leste'],
  TT: [
    'Trinidad and Tobago',
    'trinidad and tobago',
    'republic of trinidad and tobago',
  ],
  TN: ['Tunisia', 'tunisia', 'republic of tunisia'],
  TR: ['Turkey', 'turkey', 'republic of turkey'],
  TW: ['Taiwan', 'taiwan', ''],
  TZ: ['Tanzania', 'tanzania', 'united republic of tanzania'],
  UG: ['Uganda', 'uganda', 'republic of uganda'],
  UA: ['Ukraine', 'ukraine', 'ukraine'],
  UY: ['Uruguay', 'uruguay', 'oriental republic of uruguay'],
  US: ['United States', 'United States of America', 'united states of america'],
  UZ: ['Uzbekistan', 'uzbekistan', 'republic of uzbekistan'],
  VE: ['Venezuela', 'venezuela', 'bolivarian republic of venezuela'],
  VN: ['Vietnam', 'vietnam', 'socialist republic of vietnam', 'viet nam'],
  VU: ['Vanuatu', 'vanuatu', 'republic of vanuatu'],
  YE: ['Yemen', 'yemen', 'republic of yemen'],
  ZA: ['South Africa', 'south africa', 'republic of south africa'],
  ZM: ['Zambia', 'zambia', 'republic of zambia'],
  ZW: ['Zimbabwe', 'zimbabwe', 'republic of zimbabwe'],
  MT: ['Malta'],
  LI: ['Liechtenstein'],
  SG: ['Singapore'],
  BH: ['Bahrain'],
  MV: ['Maldives'],
  SM: ['San Marino'],
  VA: ['Holy See', 'holy see (vatican city)'],
  AD: ['Andorra'],
  MC: ['Monaco'],
  PF: ['French Polynesia'],
  FO: ['Faroe Islands'],
  GI: ['Gibraltar'],
  GG: ['Guernsey'],
  GF: ['French Guiana'],
  MQ: ['Martinique'],
  MF: ['Saint Martin'],
  BL: ['Saint Barthelemy'],
}

export default COUNTRY_CODES
