export default [
  { code: 'AL', names: ['Alabama'] },
  { code: 'AK', names: ['Alaska'] },
  { code: 'AZ', names: ['Arizona'] },
  { code: 'AR', names: ['Arkansas'] },
  { code: 'CA', names: ['California'] },
  { code: 'CO', names: ['Colorado'] },
  { code: 'CT', names: ['Connecticut'] },
  { code: 'DE', names: ['Delaware'] },
  { code: 'DC', names: ['District of Columbia', 'Washington D.C.'] },
  { code: 'FL', names: ['Florida'] },
  { code: 'GA', names: ['Georgia'] },
  { code: 'HI', names: ['Hawaii'] },
  { code: 'ID', names: ['Idaho'] },
  { code: 'IL', names: ['Illinois'] },
  { code: 'IN', names: ['Indiana'] },
  { code: 'IA', names: ['Iowa'] },
  { code: 'KS', names: ['Kansas'] },
  { code: 'KY', names: ['Kentucky'] },
  { code: 'LA', names: ['Louisiana'] },
  { code: 'ME', names: ['Maine'] },
  { code: 'MD', names: ['Maryland'] },
  { code: 'MA', names: ['Massachusetts'] },
  { code: 'MI', names: ['Michigan'] },
  { code: 'MN', names: ['Minnesota'] },
  { code: 'MS', names: ['Mississippi'] },
  { code: 'MO', names: ['Missouri'] },
  { code: 'MT', names: ['Montana'] },
  { code: 'NE', names: ['Nebraska'] },
  { code: 'NV', names: ['Nevada'] },
  { code: 'NH', names: ['New Hampshire'] },
  { code: 'NJ', names: ['New Jersey'] },
  { code: 'NM', names: ['New Mexico'] },
  { code: 'NY', names: ['New York'] },
  { code: 'NC', names: ['North Carolina'] },
  { code: 'ND', names: ['North Dakota'] },
  { code: 'OH', names: ['Ohio'] },
  { code: 'OK', names: ['Oklahoma'] },
  { code: 'OR', names: ['Oregon'] },
  { code: 'PA', names: ['Pennsylvania'] },
  { code: 'RI', names: ['Rhode Island'] },
  { code: 'SC', names: ['South Carolina'] },
  { code: 'SD', names: ['South Dakota'] },
  { code: 'TN', names: ['Tennessee'] },
  { code: 'TX', names: ['Texas'] },
  { code: 'UT', names: ['Utah'] },
  { code: 'VT', names: ['Vermont'] },
  { code: 'VA', names: ['Virginia'] },
  { code: 'WA', names: ['Washington'] },
  { code: 'WV', names: ['West Virginia'] },
  { code: 'WI', names: ['Wisconsin'] },
  { code: 'WY', names: ['Wyoming'] },
  { code: 'AS', names: ['American Samoa'] },
  { code: 'GU', names: ['Guam'] },
  { code: 'MH', names: ['Marshall Islands'] },
  { code: 'FM', names: ['Micronesia'] },
  { code: 'MP', names: ['Northern Marianas'] },
  { code: 'PW', names: ['Palau'] },
  { code: 'PR', names: ['Puerto Rico'] },
  { code: 'VI', names: ['Virgin Islands'] },
]
